'use strict';
//js modules
import './preloader';
import './firebase';
import './trending-page';
import './MovieDetailsModal';
import './search';
import './modalRegistration';
import './components/header/menu';
import './ourTeam';
import './pagination';
import './mainScrollUp';
